#ifndef GUARD_CONSTANTS_NEW_SHOP_H
#define GUARD_CONSTANTS_NEW_SHOP_H

// constants for specific type of shop used

enum NewShop_MartTypes {
    NEW_SHOP_TYPE_NORMAL = 0,
    NEW_SHOP_TYPE_VARIABLE,
    NEW_SHOP_TYPE_COINS,
    NEW_SHOP_TYPE_POINTS,
    NEW_SHOP_TYPE_DECOR,
    NEW_SHOP_TYPE_DECOR2,
    #ifdef MUDSKIP_OUTFIT_SYSTEM
    NEW_SHOP_TYPE_OUTFIT,
    #endif // MUDSKIP_OUTFIT_SYSTEM
};

enum NewShop_PriceTypes {
    NEW_SHOP_PRICE_TYPE_NORMAL = 0,
    NEW_SHOP_PRICE_TYPE_VARIABLE,
    NEW_SHOP_PRICE_TYPE_COINS,
    NEW_SHOP_PRICE_TYPE_POINTS,
};

#endif // GUARD_CONSTANTS_NEW_SHOP_H
